apiVersion: batch/v1
kind: Job
metadata:
  name: job-react
  namespace: learnbydo
spec:
  template:
    spec:
      containers:
      - name: frontend-react
        image: noppachai/server:1.1
        command: ['/bin/sh', '-c']
        args: ["echo 'Hello Frontend REACT. Create by Job.'"]
      restartPolicy: Never
  backoffLimit: 3