apiVersion: v1
kind: Service
metadata:
  name: frontend-react-service
  namespace: learnbydo
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - port: 2000
    targetPort: 8080
    nodePort: 32001
  selector:
    app: frontend